language: node_js

services:
    - docker
env:
  - DBUSERNAME=simon DBPASSWORD=123
before_install:
  - docker build -t nodeserver ./backend
  - docker network create node_server
  - docker run -p 27017:27017 -d --rm --network node_server -v $PWD/data:/data/db -e MONGODB_USER="$DBUSERNAME" -e MONGODB_DATABASE="test" -e MONGODB_PASS="$DBPASSWORD" --name nodeDatabase mongo:latest
  - cd backend
  - docker run -p 8080:8080 -it --network node_server -e DBUSERNAME=$DBUSERNAME -e DBPASSWORD=$DBPASSWORD -v $PWD/data:/app --name nodeServ --rm nodeserver /bin/sh -c "cd /app; npm test"
#script:
#  - npm test
