language: node_js

node_js:
    - '11'
services:
  - docker

before_install:
- docker run -p 27017:27017 --rm  -d  -v $(pwd)/database/data:/data/db --name nodeDatabase mongo:latest

script:
  - cd ./backend/data
  - npm install 
- npm run test || travis_terminate 1