services:
    - docker
before_install:
  - docker network create node_server
  - docker-compose build
#  - docker-compose run 
script:
  - docker-compose --exit-code-from backend
  - docker stop $(docker ps -qa)
  
  
  #- docker build -t nodeserver ./backend
  #- cd database
  #- docker run -p 27017:27017 -d --rm --network node_server -v $PWD/data:/data/db --name nodeDatabase mongo:latest
  #- echo "mongo\ndb.createUser({user:'simon', pwd:'123', roles:[{role:'readWrite', db:'test'}]})\nexit" | docker exec nodeDatabase \bin\bash
#
#  - cd ../backend
 # - docker run -p 8080:8080 -it --network node_server -e DBUSERNAME=simon -e DBPASSWORD=123 -v $PWD/backend/data:/app --name nodeServ --rm nodeserver /bin/sh -c "cd /app; npm test"
#   echo "mongo\ndb.createUser({user:'simon', pwd:'123', roles:[{role:'readWrite', db:'test'}]})\nexit" | docker exec nodeDatabase bash
