version: '3'

services: 
  nodeDatabase:
    image: mongo:latest
    environment:
      MONGODB_USER: "${db_user_env}"
      MONGODB_DATABASE: "${dbname_env}"
      MONGODB_PASS: "${db_pass}"
    ports:
      - "27017:27017"
    networks: 
      - backend
    volumes:
      - mongo_data:/data/db

  backend:
      build: ./backend
      environment: 
        - DBUSERNAME:simon
        - DBPASSWORD:123
      ports:
        - "8080:8080"
      networks: 
      - backend
      volumes:
        - ./backend/data:/app
      depends_on: 
        - nodeDatabse


volumes:
   mongo_data:
networks:
  backend:
    external:
      name: node_server
