version: '3.5'

services: 
  nodeDatabse:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - node_server
    volumes:
      - mongo_data/data:/data/db

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment: 
        - DBUSERNAME:simon
        - DBPASSWORD:123
      ports:
        - "8080:8080"
      networks: 
      - node_server
      volumes:
        - ./data:/app


volumes:
   mongo_data:
networks:
  node_server:
    name: node_server
    driver: custom-driver-1
