version: '3'

services: 
  nodeDatabse:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - backend
    volumes:
      - mongo_data/data:/data/db

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment: 
        - DBUSERNAME:simon
        - DBPASSWORD:123
      ports:
        - "8080:8080"
      networks: 
      - backend
      volumes:
        - ./data:/app


volumes:
   mongo_data:
networks:
  backend:
    external:
      name: node_server
