version: '3'

services: 
  nodeDatabase:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - backend
    volumes:
      - mongo_data:/data/db

  backend:
      build: ./backend
      ports:
        - "8080:8080"
      networks: 
      - backend
      volumes:
        - ./backend/data:/app
      depends_on: 
        - nodeDatabase


volumes:
   mongo_data:
networks:
  backend:
    external:
      name: node_server
